site_name: Wintersys Projects

theme:
  name: readthedocs
  logo: assets/wintersys.png
#  analytics:
#    gtag: G-0LG1QFHZ92

extra_css:
 - stylesheets/extra.css

not_in_nav: |
  TutorialsMenu.md 
  index.md
  DrupalDemos.md
  JoomlaDemos.md
  MoodleDemos.md
  QuickStartDemosPrepBeginnerLevel.md
  QuickStartDemosPrepExpertLevel.md
  SetupSSHKeysOnLaptop.md
  VirginCMSDemos.md
  WordpressDemos.md
  CustomisedDemos.md
  ExampleDemos.md
  ExampleStackScriptOverride.md


#extra:
#  generator: false
#  analytics:
#    provider: google
#    property: G-0LG1QFHZ92
#    feedback:
#      title: Was this page helpful?
#      ratings:
#        - icon: material/thumb-up-outline
#          name: This page was helpful
#          data: 1
#          note: >-
#            Thanks for your feedback, glad we could help!
#        - icon: material/thumb-down-outline
#          name: This page could be improved
#          data: 0
#          note: >-
#            Thanks for your feedback! Help us improve this page by reporting in <a href="https://service.celum.com">our support portal</a>.
#  consent:
#    title: Cookie consent
#    description: >-
#      We use cookies to provide multi-media content, to recognise your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to make our documentation better.
#    actions:
#      - reject
#      - manage
#      - accept
#    cookies:
#      analytics:
#        name: Google Analytics
#        checked: false

#extra:
#  feedback:
#    title: Was this page helpful?
#    ratings:
#      - icon: material/thumb-up-outline
#        name: This page was helpful
#        data: 1
#        note: >-
#          Thanks for your feedback, glad we could help!
#      - icon: material/thumb-down-outline
#        name: This page could be improved
#        data: 0
#        note: >-
#          Thanks for your feedback! Help us improve this page by reporting in <a href="https://service.celum.com">our support portal</a>.
#consent:
#  title: Cookie consent
#  description: >-
#      We use cookies to provide multi-media content, to recognise your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to make our documentation better.
#  actions:
#      - reject
#      - manage
#      - accept
#  cookies:
#    analytics:
#      name: Google Analytics
#      checked: false

copyright: >
  Copyright &copy; 2025 Peter Charles Winter –


