site_name: Wintersys Projects

theme:
  name: readthedocs
  logo: assets/wintersys.png
  analytics:
    gtag: G-0LG1QFHZ92

extra_css:
 - stylesheets/extra.css

not_in_nav: |
  TutorialsMenu.md 
  index.md
  DrupalDemos.md
  JoomlaDemos.md
  MoodleDemos.md
  QuickStartDemosPrepBeginnerLevel.md
  QuickStartDemosPrepExpertLevel.md
  SetupSSHKeysOnLaptop.md
  VirginCMSDemos.md
  WordpressDemos.md
  CustomisedDemos.md
  ExampleDemos.md
  ExampleStackScriptOverride.md

extra:
  consent:
    actions:
      - accept
      - manage 

copyright: >
  Copyright &copy; 2025 Peter Charles Winter –
  <a href="#__consent">Change cookie settings</a>

plugins:
  - privacy

