site_name: Wintersys Projects

theme:
  name: readthedocs
  logo: assets/wintersys.png
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
 - stylesheets/extra.css

not_in_nav: |
  TutorialsMenu.md 
  index.md
  DrupalDemos.md
  JoomlaDemos.md
  MoodleDemos.md
  QuickStartDemosPrepBeginnerLevel.md
  QuickStartDemosPrepExpertLevel.md
  SetupSSHKeysOnLaptop.md
  VirginCMSDemos.md
  WordpressDemos.md
  CustomisedDemos.md
  ExampleDemos.md
  ExampleStackScriptOverride.md

copyright: >
  Copyright &copy; 2025 Peter Charles Winter


