site_name: Wintersys Projects

theme:
  name: mkdocs
  logo: assets/wintersys.png
  palette:
    primary: orange

extra_css:
 - stylesheets/extra.css

not_in_nav: |
  TutorialsMenu.md 
  index.md
  DrupalDemos.md
  JoomlaDemos.md
  MoodleDemos.md
  QuickStartDemosPrepBeginnerLevel.md
  QuickStartDemosPrepExpertLevel.md
  SetupSSHKeysOnLaptop.md
  VirginCMSDemos.md
  WordpressDemos.md
  CustomisedDemos.md
  ExampleDemos.md
  ExampleStackScriptOverride.md

copyright: >
  Copyright &copy; 2025 Peter Charles Winter


