site_name: Wintersys Projects

theme:
  name: readthedocs
  logo: assets/wintersys.png

extra_css:
  - stylesheets/extra.css

not_in_nav: |
  TutorialsMenu.md 
  index.md
  DrupalDemos.md
  JoomlaDemos.md
  MoodleDemos.md
  QuickStartDemosPrepBeginner.md
  QuickStartDemosPrepExpert.md
  SetupSSHKeysOnLaptop.md
  VirginCMSDemos.md
  WordpressDemos.md

