site_name: Wintersys Projects

theme:
  name: readthedocs
  logo: assets/wintersys.png

extra_css:
  - stylesheets/extra.css

not_in_nav: |
  TutorialsMenu.md 
  index.md
  DrupalDemos.md
  JoomlaDemos.md
  MoodleDemos.md
  QuickStartDemosPrepBeginnerLevel.md
  QuickStartDemosPrepExpertLevel.md
  SetupSSHKeysOnLaptop.md
  VirginCMSDemos.md
  WordpressDemos.md
  CustomisedDemos.md
  ExampleDemos.md
  ExampleStackScriptOverride.md

  extra:
  analytics:
    provider: google
    property: G-0LG1QFHZ92

